### ISSUE TITLE
How to set my summary home page back.

### ISSUE THREAD

**Issue by lanredestiny** [wpexplorer/wpex-powered#1]
I change my blog homepage summary to 0, I did this through the costume>general home setting>entry. After I changed it to 0, I can't change the full article on the homepage to summery anymore. Please kindly help me with this. With the powered them.

**Comment by wpexplorer** [comment]
Sorry for the delayed reply, I never got an email notification fort his issue. I am releasing version 1.1 of the theme today and it will include the fix.

I will also be soon releasing a new plugin called "WPEX Theme Updater" so you can easily update the themes via the WP dashboard if you'd like. If not you can always re-download the theme from here and update manually.

Thanks for bringing this to my attention!

In case you are curious about what update fixes this issue to apply a manual fix, the edit is to open the file at inc/customizer-config.php and remove this line:

<pre>
'active_callback' => 'pwd_has_custom_excerpt'
</pre>

From around line 264
